# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wE4fCwLCXMwj_5XcSQw4qmY8swAw9UhB
"""

!pip install -q gradio transformers torch reportlab

import gradio as gr
import re
from datetime import datetime
from reportlab.pdfgen import canvas

schema = {
    "users": ["id","name","email","signup_date","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

dangerous_keywords = [
    "DROP","DELETE","ALTER","TRUNCATE","INSERT","UPDATE","EXEC","EXECUTE"
]

def is_safe(query):

    q = query.upper()

    for keyword in dangerous_keywords:
        if keyword in q:
            return False

    if ";" in query or "--" in query:
        return False

    return True

def get_table_name(text):

    text = text.lower()

    if any(word in text for word in ["user","users","customer","account"]):
        return "users"

    if any(word in text for word in ["order","orders","purchase","buy"]):
        return "orders"

    if any(word in text for word in ["product","products","item"]):
        return "products"

    if any(word in text for word in ["transaction","payment","transfer"]):
        return "transactions"

    return None

def get_columns(text):

    text = text.lower()

    columns = []

    if "name" in text:
        columns.append("name")

    if "email" in text:
        columns.append("email")

    if "age" in text:
        columns.append("age")

    if "amount" in text or "price" in text:
        columns.append("amount")

    if not columns:
        return "*"

    return ", ".join(columns)

def extract_conditions(text):

    conditions = []

    amount_match = re.search(r'greater than (\d+)', text)

    if amount_match:
        conditions.append(f"amount > {amount_match.group(1)}")

    if "last week" in text:
        conditions.append("DATE(date) >= DATE('now','-7 days')")

    if "last month" in text:
        conditions.append("DATE(signup_date) >= DATE('now','-1 month')")

    return conditions

query_history = []

def generate_sql(user_input):

    if not is_safe(user_input):
        return "⚠️ Security Warning: Dangerous SQL detected!"

    table = get_table_name(user_input)

    if table is None:
        return "❌ Could not detect table."

    columns = get_columns(user_input)

    conditions = extract_conditions(user_input)

    query = f"SELECT {columns} FROM {table}"

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    query += " LIMIT 10"

    query_history.append((user_input,query))

    return query

def export_pdf():

    file_name = "query_report.pdf"

    c = canvas.Canvas(file_name)

    y = 800

    c.drawString(200,820,"SQL Query Report")

    for i,(question,sql) in enumerate(query_history):

        c.drawString(50,y,f"Query {i+1}")

        y -= 20

        c.drawString(50,y,f"User: {question}")

        y -= 20

        c.drawString(50,y,f"SQL: {sql}")

        y -= 40

    c.save()

    return file_name

def chat(user_input):

    sql = generate_sql(user_input)

    return sql

with gr.Blocks() as demo:

    gr.Markdown("# NL2SQL Smart Engine")
    gr.Markdown("AI-Powered Database Query Generator")

    user_input = gr.Textbox(label="Enter your question")

    output = gr.Textbox(label="Generated SQL Query")

    generate_btn = gr.Button("Generate SQL")

    pdf_btn = gr.Button("Export PDF")

    generate_btn.click(chat,inputs=user_input,outputs=output)

    pdf_btn.click(export_pdf,outputs=gr.File())

demo.launch(share=True)